### PR TITLE
Changes from QGIS review at Vienna Code Sprint

### PR DESCRIPTION
**Pull request by kalxas**
Thanks Anita, Richard and Tim

### CODE REVIEW

**Comment by kalxas** [comment]
thanks

**Comment by tomkralidis** [comment]
@kalxas / @rduivenvoorde et al: thanks for this. FYI see below screenshot.  Any ideas on how to maintain layout w/ resizing?  

metasearch-ui-issues

**Comment by kalxas** [comment]
Plus I see that the buttons are not the same size under the results...

**Comment by rduivenvoorde** [comment]
anybody looking into this? Otherwise I do this as part of https://github.com/geopython/MetaSearch/issues/25#issuecomment-39076723

**Comment by tomkralidis** [comment]
@rduivenvoorde great, sounds good, thanks.

**Pull request merged**
